name: 'GSA Setup'
description: 'Setting up for testing with GSA'
runs:
  using: "composite"
  steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: python3 -m pip install git+https://github.com/mailund/pystr#egg=pystr
        shell: bash
      - run: python3 -m pip install git+https://github.com/mailund/gsa#egg=gsa
        shell: bash
